config/routes.rb
Rails.application.routes.draw do
  
  resources :users

  root 'pages#home'
  
  get 'pages/sign_in' => 'pages#sign_in' 

  get 'pages/about' => 'pages#about' 

  get 'pages/signup' => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
# attr_accessor :name, :email
 # validates :name, presence: true
 # validates :name, length: { maximum: 11}
 # validates :email, confirmation: true
 # validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
 # validates :email, uniqueness: true
 # validates :email, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
  end

  def sign_in
  	@title = "Sign in"

  end

  def about
  	@title = "About"
  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
	def index
	end


  def new
  
  @title = "Sign up" 

  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class = "round">
    <nav class= "round">
    	<ul>
    		<%= link_to "Home", root_path %>
    		<%= link_to "About", pages_about_path %>
    		<%= link_to "Sign in", pages_sign_in_path %>
        </ul>
    </nav>
    </header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oki | <%= @title %></title>
  <%= render 'layouts/stylesheets' %>  
</head>
<body>
	<div class = "container">
	<%= render 'layouts/header' %>  
    <section class= "round">
<%= yield %>
</section>

</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<%= link_to "Sign Up", '', :class => "sign_up_button round" %>

app/views/pages/sign_in.html.erb
<h1>Pages#sign_in</h1>
<p>Find me in app/views/pages/sign_in.html.erb</p>

app/views/users/index.html.erb
Hellp

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>